/// [Document.fromJson]용 샘플 Delta ops (이미지·비디오 임베드 없음).
///
/// 공식 예제 `flutter_quill` 패키지의 `quill_delta_sample.dart` 구조를 따르며,
/// 학습용으로 헤더·목록·인용·코드·정렬·링크·체크리스트·들여쓰기·폰트·색 등을 포함합니다.
List<Map<String, dynamic>> quillLearningSampleOps() => [
      {'insert': 'Flutter Quill 학습 샘플\n'},
      {'attributes': {'header': 1}, 'insert': '\n'},
      {'insert': '패키지: '},
      {
        'attributes': {'link': 'https://pub.dev/packages/flutter_quill'},
        'insert': 'flutter_quill',
      },
      {'insert': ' — WYSIWYG 리치 텍스트 에디터(Quill Delta 기반).\n\n'},
      {'insert': '인라인 스타일\n'},
      {'attributes': {'header': 2}, 'insert': '\n'},
      {'insert': '굵게·기울임·밑줄·취소선·코드·위첨자·아래첨자·작은글씨를 툴바에서 전환해 보세요. '},
      {'attributes': {'bold': true}, 'insert': 'Bold'},
      {'insert': ' '},
      {'attributes': {'italic': true}, 'insert': 'Italic'},
      {'insert': ' '},
      {'attributes': {'underline': true}, 'insert': 'Underline'},
      {'insert': ' '},
      {'attributes': {'strike': true}, 'insert': 'Strike'},
      {'insert': ' '},
      {'attributes': {'code': true}, 'insert': 'inline code'},
      {'insert': ' '},
      {'attributes': {'script': 'super'}, 'insert': 'sup'},
      {'insert': ' '},
      {'attributes': {'script': 'sub'}, 'insert': 'sub'},
      {'insert': '\n\n'},
      {'insert': '색상과 배경\n'},
      {'attributes': {'header': 3}, 'insert': '\n'},
      {'attributes': {'color': '#1565c0'}, 'insert': '전경색'},
      {'insert': ' '},
      {
        'attributes': {'background': '#fff9c4'},
        'insert': '배경 강조',
      },
      {'insert': '\n\n'},
      {'insert': '블록: 인용 · 코드 · 목록\n'},
      {'attributes': {'header': 2}, 'insert': '\n'},
      {'insert': '인용문은 블록쿼트로 표시됩니다.'},
      {'attributes': {'blockquote': true}, 'insert': '\n'},
      {'insert': "final hello = 'Dart';"},
      {'attributes': {'code-block': true}, 'insert': '\n'},
      {'insert': '순서 목록'},
      {'attributes': {'list': 'ordered'}, 'insert': '\n'},
      {'insert': '두 번째 항목'},
      {'attributes': {'list': 'ordered'}, 'insert': '\n'},
      {'insert': '중첩 항목'},
      {'attributes': {'indent': 1, 'list': 'ordered'}, 'insert': '\n'},
      {'insert': '글머리 기호'},
      {'attributes': {'list': 'bullet'}, 'insert': '\n'},
      {'insert': '하위 글머리'},
      {'attributes': {'indent': 1, 'list': 'bullet'}, 'insert': '\n'},
      {'insert': '체크리스트(완료)'},
      {'attributes': {'list': 'checked'}, 'insert': '\n'},
      {'insert': '체크리스트(미완료)'},
      {'attributes': {'list': 'unchecked'}, 'insert': '\n'},
      {'insert': '\n'},
      {'insert': '정렬 · RTL · 들여쓰기\n'},
      {'attributes': {'header': 2}, 'insert': '\n'},
      {'insert': '가운데 정렬 줄'},
      {'attributes': {'align': 'center'}, 'insert': '\n'},
      {'insert': '오른쪽 정렬'},
      {'attributes': {'align': 'right'}, 'insert': '\n'},
      {'insert': '양쪽 정렬은 긴 문단에서 차이가 드러납니다. 동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라 만세. '},
      {'attributes': {'align': 'justify'}, 'insert': '\n'},
      {'insert': 'RTL 블록 예: مرحبا'},
      {'attributes': {'direction': 'rtl'}, 'insert': '\n'},
      {'insert': '들여쓰기 단계 1'},
      {'attributes': {'indent': 1}, 'insert': '\n'},
      {'insert': '들여쓰기 단계 2'},
      {'attributes': {'indent': 2}, 'insert': '\n'},
      {'insert': '\n'},
      {'insert': '폰트 패밀리 · 크기\n'},
      {'attributes': {'header': 2}, 'insert': '\n'},
      {'insert': 'Font '},
      {'attributes': {'font': 'sans-serif'}, 'insert': 'Sans'},
      {'insert': ' '},
      {'attributes': {'font': 'serif'}, 'insert': 'Serif'},
      {'insert': ' '},
      {'attributes': {'font': 'monospace'}, 'insert': 'Mono'},
      {'insert': ' · Size '},
      {'attributes': {'size': 'small'}, 'insert': 'small'},
      {'insert': ' '},
      {'attributes': {'size': 'large'}, 'insert': 'large'},
      {'insert': ' '},
      {'attributes': {'size': 'huge'}, 'insert': 'huge'},
      {'insert': '\n\n'},
      {'insert': '실습 팁\n'},
      {'attributes': {'header': 2}, 'insert': '\n'},
      {
        'insert':
            '툴바에서 검색·링크·실행취소/다시하기·클립보드(잘라내기/복사/붙여넣기)를 써 보세요. '
            '이미지·동영상 임베드는 별도 패키지 flutter_quill_extensions가 필요합니다.\n',
      },
    ];
