// Generates lib/pages/reference/f_icons_catalog.g.dart from forui_assets assets.g.dart
// Run: dart run tool/generate_f_icons_catalog.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final projectRoot = Directory.current;
  final configFile = File('${projectRoot.path}/.dart_tool/package_config.json');
  if (!configFile.existsSync()) {
    stderr.writeln('Run `dart pub get` first.');
    exit(1);
  }
  final config = jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  final packages = config['packages'] as List<dynamic>;
  String? rootUri;
  for (final p in packages) {
    final m = p as Map<String, dynamic>;
    if (m['name'] == 'forui_assets') {
      rootUri = m['rootUri'] as String;
      break;
    }
  }
  if (rootUri == null) {
    stderr.writeln('forui_assets not in package_config.json');
    exit(1);
  }
  if (rootUri.startsWith('file:///')) {
    rootUri = Uri.parse(rootUri).toFilePath();
  } else if (rootUri.startsWith('file://')) {
    rootUri = rootUri.substring(7);
  }

  final assetsPath = '$rootUri${Platform.pathSeparator}lib${Platform.pathSeparator}src${Platform.pathSeparator}assets.g.dart';
  final src = File(assetsPath);
  if (!src.existsSync()) {
    stderr.writeln('Missing: $assetsPath');
    exit(1);
  }

  final text = src.readAsStringSync();
  final re = RegExp(r'^\s*static const (\w+) = IconData', multiLine: true);
  final names = re.allMatches(text).map((m) => m.group(1)!).toList()..sort();

  final buf = StringBuffer()
    ..writeln('// GENERATED BY tool/generate_f_icons_catalog.dart — DO NOT EDIT')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:forui_assets/forui_assets.dart';")
    ..writeln()
    ..writeln('/// All [FIcons] entries for search / gallery (Lucide via forui_assets).')
    ..writeln('abstract final class FIconsCatalog {')
    ..writeln('  FIconsCatalog._();')
    ..writeln()
    ..writeln('  static const int count = ${names.length};')
    ..writeln()
    ..writeln('  static const List<String> names = [');
  for (final n in names) {
    buf.writeln("    '$n',");
  }
  buf
    ..writeln('  ];')
    ..writeln()
    ..writeln('  static IconData iconByName(String name) {')
    ..writeln('    switch (name) {');

  for (final n in names) {
    buf.writeln("      case '$n':");
    buf.writeln('        return FIcons.$n;');
  }

  buf
    ..writeln('      default:')
    ..writeln("        throw ArgumentError.value(name, 'name', 'Unknown FIcons name');")
    ..writeln('    }')
    ..writeln('  }')
    ..writeln('}');

  final out = File('${projectRoot.path}/lib/pages/reference/f_icons_catalog.g.dart');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${names.length} icons -> ${out.path}');
}
